### ISSUE TITLE
unrecognized arguments: --n_proc 

### ISSUE THREAD

**Issue by SaeedM75** [ArleyFlorezL/gradient_cryoEM#5]
n_proc argument has not been implemented in the cal_gradient.py script.

**Comment by DSilva27** [comment]
Hi Saeed, did you switch to the develop branch? It is not yet implemented in main.

I'll set develop as the default branch to avoid this kind of errors in the future, thank you

**Comment by SaeedM75** [comment]
Hi David. You're right and I forgot to switch to the development branch. I just did and found it implemented.
